# Generated by Django 4.1.7 on 2023-02-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='hhjjnkj', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
